name: Test pdeffer
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install WeasyPrint requirements
        run: sudo apt-get install build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
      - name: Install Virtual Env requirements
        run: sudo apt-get install python3-venv
      - name: Create Virtual Env
        run: python3 -m venv .venv
      - name: Install python requirements
        run: .venv/bin/pip install -r requirements.txt
      - name: Check Format
        run: .venv/bin/black . --check